### ISSUE TITLE
Could not create inference context

### ISSUE THREAD

**Issue by muzammil-triffort** [artemnovichkov/StickerViewExample#1]
Getting following error: Error Domain=com.apple.Vision Code=9 "Could not create inference context" UserInfo={NSLocalizedDescription=Could not create inference context}

**Comment by artemnovichkov** [comment]
Did you run the example on a simulator? Try to run on a real device.

**Comment by muzammil-triffort** [comment]
Hi @artemnovichkov, Yes I figure it out that it works on real device only. Your code works perfectly :-)
